### ISSUE TITLE
Provide binaries to install for Linux and Windows too

### ISSUE THREAD

**Issue by karuppiah7890** [thecasualcoder/tztail#14]
@aswinkarthik 
Seeing the traction the repo is getting, I am guessing there will be some Linux and Windows users too. Currently there's an easy way to install for Mac users - `brew` or get the release from releases page. I see there's no release or installation method mentioned for Linux or Windows users. It would be great to see a word on it in the readme. What do you think ?

**Comment by aswinkarthik** [comment]
Linux binaries are available in releases. Windows users can install using `cargo`. Closing issue.
