### ISSUE TITLE
Error when trying to compile the version 1.1.0 under WSL

### ISSUE THREAD

**Issue by fitchtravis** [thecasualcoder/tztail#24]
Running `rustc --crate-name tztail src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=3eb2f260398f03f7 -C extra-filename=-3eb2f260398f03f7 --out-dir /home/m16389/code/tztail/target/release/deps -L dependency=/home/m16389/code/tztail/target/release/deps --extern chrono=/home/m16389/code/tztail/target/release/deps/libchrono-9b8ba4e87cc7f434.rlib --extern chrono_tz=/home/m16389/code/tztail/target/release/deps/libchrono_tz-433a6eb3d17e14ec.rlib --extern clap=/home/m16389/code/tztail/target/release/deps/libclap-ba7047d08a1758e4.rlib --extern hourglass=/home/m16389/code/tztail/target/release/deps/libhourglass-c86c147ca25af4a4.rlib --extern regex=/home/m16389/code/tztail/target/release/deps/libregex-dc40b0fae605236f.rlib`
error[E0599]: no method named `trim_end` found for type `std::string::String` in the current scope
  --> src/main.rs:50:51
   |
50 |                     println!("{}", c.convert(&buf.trim_end()));
   |                                                   ^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `tztail`.

Caused by:
  process didn't exit successfully: `rustc --crate-name tztail src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=3eb2f260398f03f7 -C extra-filename=-3eb2f260398f03f7 --out-dir /home/m16389/code/tztail/target/release/deps -L dependency=/home/m16389/code/tztail/target/release/deps --extern chrono=/home/m16389/code/tztail/target/release/deps/libchrono-9b8ba4e87cc7f434.rlib --extern chrono_tz=/home/m16389/code/tztail/target/release/deps/libchrono_tz-433a6eb3d17e14ec.rlib --extern clap=/home/m16389/code/tztail/target/release/deps/libclap-ba7047d08a1758e4.rlib --extern hourglass=/home/m16389/code/tztail/target/release/deps/libhourglass-c86c147ca25af4a4.rlib --extern regex=/home/m16389/code/tztail/target/release/deps/libregex-dc40b0fae605236f.rlib` (exit code: 101)

**Comment by leethomas** [comment]
Hi @fitchtravis , what does the output of `rustc --version` say for you? It looks like the `trim_end` API became stable in `1.30.0`: https://doc.rust-lang.org/nightly/std/primitive.str.html#method.trim_end

Assuming you're running a version of `rustc` pre `1.30.0`, does it resolve itself when you upgrade?

**Comment by fitchtravis** [comment]
Hi @leethomas, I was running rustc 1.28. Upgrading to 1.30 resolved the issue. Thanks for your help

**Comment by aswinkarthik** [comment]
I will add this to README. Thank you @leethomas
